version: '2'
services:
  api:
    build:
      context: "./api"
    hostname: api
    ports:
      - "9000:9000"
  client:
    build:
      context: "./client"
      dockerfile: Dockerfile-prod
    hostname: react
    links:
      - api
    ports:
      - "80:80"
